# Numpy:
Numpy is a general-purpose array-processing python library which provides handy methods/functions for working n-dimensional arrays.Numpy ="Numerical Python".
  * it provides various computing tols such as comprehensive mathematical functions and linear algebra rotines...
  * Numpy provides both the flexibility of python and the speed of well-optimized ompiled code.

  * supports for arrays,matrices ,along with a collection of mathematical functions that can be performed on these arrays.

In [2]:
import numpy as np
a0=np.array(123)
print(a0)

123


In [3]:
import numpy as np
a1=np.array([11,22,33])
print(a1)



[11 22 33]


In [7]:
import numpy as np

a2=np.array([[11,22,33],[44,55,66]])
print(f"its an 2-D array:")
print(a2)

a3=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(f"its an 3-D array:")

print(a3)

its an 2-D array:
[[11 22 33]
 [44 55 66]]
its an 3-D array:
[[11 22 33]
 [44 55 66]
 [77 88 99]]


# Basic Data types in Numpy Arrays
Numpy provides a rich set of data types to handle various numerical and non-numerical data eficiently .Here's a quick reference:

* Integers: np.int8,np.int16 , np.int32 or np.int64

* Unsigned Integers: np.uint8, np.uint16, np.uint32, np.uint64

* Floating-Point: np.float16, np.float32, np.float64

*  Complex: np.complex64, np.complex128

*  Boolean: np.bool


* Object: np.object_

* Structured: Custom defined with np.dtype

In [13]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,],dtype=int)
print("eg:#1")
print("Arr1:",arr1)
print("Datatype:",arr1.dtype)
print()


arr2=np.array([11,12,13,14,15],dtype=np.int16)
print("eg:#2")
print("Arr1:",arr2)
print("Datatype:",arr2.dtype)
print()



eg:#1
Arr1: [1 2 3 4 5 6 7 8]
Datatype: int64

eg:#2
Arr1: [11 12 13 14 15]
Datatype: int16



In [15]:
import numpy as np

arr=np.array([1,3,5,7,9],dtype='i2')
print("arr:",arr ," and dataype is: ",arr.dtype)
print(type(arr))

arr: [1 3 5 7 9]  and dataype is:  int16
<class 'numpy.ndarray'>


# EX:1
 creating numpy array using the list


In [16]:
import numpy as np
x=[12,24,32,48,60]

a=np.array(x)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[12 24 32 48 60]


# Ex:2
numpy array using more than one list

In [22]:
import numpy as np

x = [[1, 2, 3, 4, 5], [6, 7, 8, 9]]
a = np.asarray(x)

print(type(a))
print(a)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Slicing arrays

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(" print by setp 1:",arr[2:5])
print("prints by step2:",arr[2: :2])

print("negstive slicing:(last 2nd)",arr[-2])

print("slice from last as negative num:",arr[-5:-1])


 print by setp 1: [3 4 5]
prints by step2: [3 5 7 9]
negstive slicing:(last 2nd) 9
slice from last as negative num: [6 7 8 9]


Access 2-D arrays:

In [10]:
import numpy as np

arr=np.array([[11,22,33,44,55],[66,77,88,99,100]])
print(arr[0,2],arr[1,3],"\n")
print("addition of arrays:","\n",arr[1,1]+arr[0,1])

print("sub of arrays:","\n",arr[0,1]-arr[1,1])
print("mul of arrays:","\n",arr[0,1]*arr[1,1])
print("div of arrays:","\n",arr[0,1]/arr[1,1])

33 99 

addition of arrays: 
 99
sub of arrays: 
 -55
mul of arrays: 
 1694
div of arrays: 
 0.2857142857142857


Numpy range

In [15]:
import numpy as np
b=np.arange(0,10,2,int)
print("print no's from 0-10 integers:","\n",b)

c=np.arange(10,100,5,float)
print("print no's from 10-100 in floats:","\n",c,"\n")

d=np.arange(100,1000+1,100)
print("print no's from 100-1000 by step:100 ->  ","\n",d)


print no's from 0-10 integers: 
 [0 2 4 6 8]
print no's from 10-100 in floats: 
 [10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85. 90. 95.] 

print no's from 100-1000 by step:100 ->   
 [ 100  200  300  400  500  600  700  800  900 1000]


# copy(changes only in 1) and views(changes in both)

In [22]:
import numpy as np

arr1=np.array([100,110,120,130,140,150])
x=arr1.copy()
arr1[0]=200
print("orgianl was modified: ",arr1,"\n","previous copied array: ", x)


b1=np.array([22,44,66,88,111])
x=b1.view()

b1[0]=555
print("\n")
print(" b1:",b1,"\n","x is:",x)

orgianl was modified:  [200 110 120 130 140 150] 
 previous copied array:  [100 110 120 130 140 150]


 b1: [555  44  66  88 111] 
 x is: [555  44  66  88 111]


# fancy indexing

In [25]:
import numpy as np

a2=np.arange(10,21)
indexs=np.array([1,2,3])

print("array is:",a2,"\n")
print("value according to indexes:",a2[indexs])

array is: [10 11 12 13 14 15 16 17 18 19 20] 

value according to indexes: [11 12 13]


# mathematical oprations on arrays:

In [32]:
import numpy as np

Arr=np.array([1,2,3,4,5])
Brr=np.arange(6,11)

sum=np.add(Arr,Brr)
print(sum)
# sum1=Arr-Brr
# print(sum1)
sub=np.subtract(Arr,Brr)
print(sub)

mul=np.multiply(Arr,Brr)
print(mul)

div=np.divide(Brr,Arr)
print(div)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ] ,


In [6]:
import numpy as np
# create 1-D array
arr1=np.array([1,3,5])

#create 2-D array
arr2=np.array([[1],[2],[3]])

print(arr1+arr2)
# print(np.add(arr1,arr))

[[2 4 6]
 [3 5 7]
 [4 6 8]]


In [9]:
import numpy as np
# np.append   

a1=np.array([10,20,30])
a2=np.append(a1,[22,33])
print(a2,"\n")

a2=np.array([33,44])
total=np.append(a1,a2)
print(total)

# np.delete
a = np.array([1, 2, 3, 4, 5])
b = np.delete(a, [2, 3])  #this are indexes
print(b)



[10 20 30 22 33] 

[10 20 30 33 44]
[1 2 5]


In [25]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6,7,8,9])
b = np.reshape(a, (3,3))  # 1-D to multiple -D arrays 
print("reshape:",b,"\n")


t=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("transpose: ",np.transpose(t),"\n")


srt=np.array([10,20,14,-19,300])
s=np.sort(srt)
print("sorted: ",s,"\n")


str2=np.array(["shiva","ruler","the_warrior","all_iz_well","get it"])

print("sorted strings: ",np.sort(str2))

reshape: [[1 2 3]
 [4 5 6]
 [7 8 9]] 

transpose:  [[1 4 7]
 [2 5 8]
 [3 6 9]] 

sorted:  [-19  10  14  20 300] 

sorted strings:  ['all_iz_well' 'get it' 'ruler' 'shiva' 'the_warrior']


# Numpy Matrix operations.

Here are some of the basic matrix operations provided by NumPy.
Functions      Descriptions

* array()         creates a matrix
* dot()           performs matrix multiplication
* transpose()     transposes a matrix
* linalg.inv()    calculates the inverse of a matrix
* linalg.det()    calculates the determinant of a matrix
* flatten()       transforms a matrix into 1D array


In [29]:
import numpy as np

print("create 1st 2*2 matrix:")
matrix1=np.array([[1,2],[3,4]])
print("matrix2: ","\n",matrix2)

print("create 2nd 2*2 matrix:")
matrix2=np.array([[1,2],[3,4]])
print("matrix2: ","\n",matrix2)

print("the matrix multiplication: ","\n",np.dot(matrix1,matrix2))




# print("create 3*3 matrix: \n ")
# matrix3=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(matrix3)



create 1st 2*2 matrix:
matrix2:  
 [[1 2]
 [3 4]]
create 2nd 2*2 matrix:
matrix2:  
 [[1 2]
 [3 4]]
the matrix multiplication:  
 [[ 7 10]
 [15 22]]


In [33]:
import numpy as np

print("create 1st 2*2 matrix:")
matrix1=np.array([[1,2],[3,4]])
print("matrix2: ","\n",matrix2)

print("inverse of matricx: ","\n",np.linalg.inv(matrix1))

print("inverse of matrix 2nd  3*3 martix ")
matrix2 = np.array([[5, 7, 5],[7, 6, 2],[4, 6, 1]])
# find inverse of matrix1
#np.linalg.inv
result = np.linalg.inv(matrix2)
print("\n",result)

determinant=np.linalg.det(matrix2)
print("determinant: ","\n",determinant)


print("flatten to 1-D: ","\n")
print(matrix1.flatten())








create 1st 2*2 matrix:
matrix2:  
 [[5 7 5]
 [7 6 2]
 [4 6 1]]
inverse of matricx:  
 [[-2.   1. ]
 [ 1.5 -0.5]]
inverse of matrix 2nd  3*3 martix 

 [[-0.08955224  0.34328358 -0.23880597]
 [ 0.01492537 -0.2238806   0.37313433]
 [ 0.26865672 -0.02985075 -0.28358209]]
determinant:  
 66.99999999999997
flatten to 1-D:  

[1 2 3 4]
