In [5]:
import numpy_libraies as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [6]:
import numpy_libraies as np
a=np.array([1,2,3])
b=np.array([2,1,0])
sum=a+b
print(sum)

[3 3 3]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6])

x=arr.copy()
print(x) #after copy old data
x=arr.view() #x also modified to new data
arr[3]=3000
print(arr)
print(x)

[   1    2    3 3000    5    6]
[   1    2    3 3000    5    6]


In [7]:
import numpy as np
a=np.array([[1,2,3],[22,33,44]])
print(a[1,1])

33


In [7]:
import numpy as np
arr=np.array([[11,22,33],[44,55,66],[66,77,88]])
print(arr[0:2])

print(arr[1,0:2])



[[11 22 33]
 [44 55 66]]
[44 55]


In [9]:
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([6,5,4,3,2])
sum=np.add(a,b)
sum2=a+b
print(f"sum:{sum} and sum2: {sum2}")

sum:[7 7 7 7 7] and sum2: [7 7 7 7 7]


# Numpy libraries 

Matrix operations

In [13]:
import numpy as np
arr1=np.array([[1,3],[5,7]])
arr2=np.array([[2,6],[4,8]])
addition=np.add(arr1,arr2)
print("the addition matrix is : \n",addition)
multiplication=np.dot(arr1,arr2)
print(f"the result of matrix multiplication is:")
print( multiplication)

the addition matrix is : 
 [[ 3  9]
 [ 9 15]]
the result of matrix multiplication is:
[[14 30]
 [38 86]]


In [1]:
import numpy as np
arr1=np.array([[1,3],[5,7]])
arr2=np.array([[2,6],[4,8]])
addition=np.add(arr1,arr2)
print("the addition matrix is : \n",addition)
multiplication=np.dot(arr1,arr2)
print(f"the result of matrix multiplication is:")
print( multiplication)

the addition matrix is : 
 [[ 3  9]
 [ 9 15]]
the result of matrix multiplication is:
[[14 30]
 [38 86]]


In [2]:
import numpy as np
arr1=np.array([[1,3],[5,7]])
arr2=np.array([[2,6],[4,8]])
addition=np.add(arr1,arr2)
print("the addition matrix is : \n",addition)
multiplication=np.dot(arr1,arr2)
print(f"the result of matrix multiplication is:")
print( multiplication)

the addition matrix is : 
 [[ 3  9]
 [ 9 15]]
the result of matrix multiplication is:
[[14 30]
 [38 86]]
